name: Build & Release on Tagged Commit

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python3 make.py
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/random-lyric-update-motd.sh
            dist/random-lyric-update-motd-multiline.sh
            dist/random-lyric-data.json
            dist/random-lyric-data.min.json
            dist/random-lyric-lines.txt
            dist/random-lyric-database.txt
