name: Lint on Push / Pull Request
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python3 make.py
